src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('tool.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/tool/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from reports.views import UserAddReportView, UserReportsView, UserViewReport
from tool.views import UserSupplementView, UserSupplementTransporterView, \
    UserSupplementTransporterEditView, ResultView, DownloadView, \
    UploadView, UploadCompanyFileView

app_name = "tool"

urlpatterns = [
    path('', TemplateView.as_view(template_name="tool/home.html"), name="home"),
    path('reports/add-report', UserAddReportView.as_view(), name='add-report'),
    path('reports/add-report/2', UploadView.as_view(), name='upload'),
    path('reports/add-report/3', UploadCompanyFileView.as_view(), name='upload-company-file'),
    path('transporters/', UserSupplementView.as_view(), name="transporters"),
    path('transporters/<slug:slug>', UserSupplementTransporterView.as_view(), name="tarifs"),
    path('transporters/<slug:slug>/edit', UserSupplementTransporterEditView.as_view(), name="edit-tarifs"),
    path('result/', ResultView.as_view(), name='result'),
    path('download/<slug:slug>', DownloadView.as_view(), name='download'),
    path('reports/', UserReportsView.as_view(), name='reports'),
    path('reports/<slug:slug>', UserViewReport.as_view(), name='single-report'),
]

src/tool/models.py
from django.db import models

# Create your models here.
from accounts.models import Transporter, Company, User
from reports.models import Report
from tool.helpers import validate_file_extension

PROFILE_CHOICES = [
    ('CLI', 'Client'),
    ('TRP', 'Transporteur'),
]

class CompanyFile(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)
    file = models.FileField('Insertion fichier des commandes', null=True, blank=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    header_row = models.IntegerField(default=0, null=True, blank=True)
    report = models.ForeignKey(Report, on_delete=models.CASCADE, blank=True, null=True)


    def __str__(self):
        return str(self.name)


    class Meta:
        verbose_name = "Company File"
        verbose_name_plural = "Company Files"


class TransporterFile(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)
    file = models.FileField('Insertion fichier transporteur', null=True, blank=False)
    transporter = models.ForeignKey(Transporter, on_delete=models.CASCADE, blank=True, null=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    report = models.ForeignKey(Report, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return str(self.transporter)

    class Meta:
        verbose_name = "Transporter File"
        verbose_name_plural = "Transporter Files"

src/reports/forms.py
import calendar

from bootstrap_modal_forms.forms import BSModalModelForm
from django import forms

from reports.models import Report


class ReportForm(forms.ModelForm):
    """ Form to create a report. """

    date = forms.DateField(widget=forms.widgets.DateInput(attrs={'type': 'date'}))

    class Meta:
        model = Report
        fields = ['title', 'company', ]

    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request
        user = self.request.user
        self.initial['company'] = user.company

    def clean(self):
        super().clean()
        filtered_date = self.cleaned_data.get('date')
        month = filtered_date.month
        month = calendar.month_name[month]
        year = filtered_date.year
        date_f = str(month) + " " + str(year)
        print(self.instance)
        self.request.session['date_f'] = date_f

src/tool/forms.py
import os
import sqlite3
import calendar
from pprint import pprint
import time
import numpy as np
import pandas as pd
from django import forms
from django.forms import modelformset_factory, inlineformset_factory
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.template.defaultfilters import slugify
from django_pandas.io import read_frame

from accounts.models import Transporter, Supplement, Weight, WeightPrices, Company
from reports.models import Report
from tool.helpers import parse_excel, parse_csv, parse_xml, validate_file_extension
from tool.models import TransporterFile, CompanyFile


class TransporterFileForm(forms.ModelForm):

    class Meta:
        model = TransporterFile
        fields = ('file', )
        widgets = {
        'file': forms.FileInput(attrs={'onchange': 'submit();'})
        }



class CompanyFileForm(forms.ModelForm):
    class Meta:
        model = CompanyFile
        fields = ('file', )

        def __init__(self, request, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.request = request
            user = self.request.user
            self.initial['user'] = user
            self.initial['company'] = user.company

        def clean(self):
            super().clean()
            user = self.request.user
            file = self.cleaned_data.get('file')
            print(file)

src/tool/views.py
import os
from io import BytesIO
import time
import numpy as np
import pandas as pd
import xlsxwriter
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.http import HttpResponse, JsonResponse, Http404
from django.shortcuts import render, get_object_or_404, redirect
from pprint import pprint

from django.template.defaultfilters import slugify
import plotly.graph_objects as go
from django.urls import path, reverse_lazy, reverse
from django.utils.crypto import get_random_string
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import TemplateView, CreateView, FormView, DetailView, ListView, UpdateView, DeleteView
from django_pandas.io import read_frame

from accounts.models import User, Supplement, Weight, WeightPrices, Company, Transporter, SupplementDetails
from reports.models import Report, ReportDetails
from tool.forms import TransporterFileForm, CompanyFileForm
import json

from tool.helpers import get_header_row, parse_file, analyze, store_results
from tool.models import TransporterFile, CompanyFile

pd.set_option('display.width', 400)
pd.set_option('display.max_columns', 15)


class RequestFormMixin:
    """Mixin to inject the request in the form."""

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["request"] = self.request
        return kwargs


class CustomLoginRequiredMixin(LoginRequiredMixin):
    """ The LoginRequiredMixin extended to add a relevant message to the
    messages framework by setting the ``permission_denied_message``
    attribute. """

    permission_denied_message = 'You have to be logged in to access that page'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.add_message(request, messages.WARNING,
                                 self.permission_denied_message)
            return self.handle_no_permission()
        return super(CustomLoginRequiredMixin, self).dispatch(
            request, *args, **kwargs
        )


'''
TRANSPORTERS:
View to see the list of transporters affected to one user.
'''


class UserSupplementView(CustomLoginRequiredMixin, TemplateView):
    """ View to see transporters """

    model = User
    template_name = 'tool/transporters.html'
    permission_denied_message = 'Restricted access!'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        context['supplements'] = user.company.supplement_set.all()
        print(context['supplements'])
        return context


class UserSupplementTransporterView(LoginRequiredMixin, TemplateView):
    model = Supplement
    template_name = 'tool/transporter-detail.html'
    context_object_name = "tarifs"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        slug = self.kwargs['slug']
        context['supplement'] = get_object_or_404(Supplement, slug=slug)
        return context

    def get_form_kwargs(self):
        kwargs = super(UserSupplementTransporterView, self).get_form_kwargs()
        slug = self.kwargs['slug']
        kwargs['header'] = get_object_or_404(Supplement, slug=slug).header_row
        return kwargs


'''
TRANSPORTER:
View to edit pricings of transporter.
'''


class UserSupplementTransporterEditView(LoginRequiredMixin, UpdateView):
    """ View to edit supplements """

    model = Supplement
    fields = ['supplement_annonce_incomplete', 'supplement_retour_expediteur', 'supplement_etiquette_non_conforme',
              'supplement_zone_difficile_acces', 'supplement_corse', 'supplement_manutention', 'supplement_gt',
              'supplement_carburant_routier', 'supplement_frais_de_gestion', 'supplement_facture_papier',
              'supplement_surete_colis', 'supplement_zone_internationale_eloignee',
              'supplement_surcharge_carburant_routier', 'supplement_covid', 'supplement_taxe_carbone']
    template_name = 'tool/transporter-detail-edit.html'
    context_object_name = "edit-tarifs"

    def form_valid(self, form):
        context = self.get_context_data()
        slug = self.kwargs['slug']
        form.instance.supplement = Supplement.objects.get(slug=slug)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('tool:tarifs', kwargs={'slug': self.object.slug})


class UploadView(RequestFormMixin, TemplateView):
    template_name = 'tool/upload.html'

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['formset'] = TransporterFileFormSet(queryset=TransporterFile.objects.none())
    #     context['files'] = TransporterFile.objects.all()
    #
    #     ''' Even if user is logged in, cannot access directly the URL. Have to use the form. '''
    #     # if reverse('tool:add-report') not in self.request.META.get('HTTP_REFERER'):
    #     #     raise Http404
    #
    #     return context
    #
    # def post(self, request, *args, **kwargs):
    #
    #     user = self.request.user
    #     company = get_object_or_404(Company, pk=user.company.pk)
    #     formset = TransporterFileFormSet(data=request.POST or None, files=request.FILES, instance=company)

        # if formset.is_valid():
        #
        #     dict_files = {}
        #     files_list = []
        #     transporter_list = []
        #     pk_list = []
        #
        #     for form in formset:
        #         obj = form.save(commit=False)
        #         cd = form.cleaned_data
        #         file = cd.get('file')
        #         transporter = cd.get('transporter')
        #         print(transporter)
        #         form.save()
        #         transporter_file = TransporterFile.objects.get(pk=obj.pk)
        #         n_transporter_file = TransporterFile.objects.filter(pk=obj.pk).update(name=transporter_file.file.name)
        #         n_transporter_file = TransporterFile.objects.filter(pk=obj.pk).update(user=user)
        #         pk_list.append(obj.pk)
        #         files_list.append(transporter_file.file.name)
        #         transporter_list.append(transporter.name)
        #         print(transporter_list)
        #         dict_files['pk'] = pk_list
        #         dict_files['files'] = files_list
        #         dict_files['transporter'] = transporter_list
        #         request.session['dict_files'] = dict_files
        #
        #     return redirect('tool:upload-company-file')
        #
        #
        #
        # else:
        #     raise ValidationError('You cannot submit empty form.')
        #
        # return self.render_to_response({'formset': formset})


class UploadCompanyFileView(LoginRequiredMixin, CreateView):
    model = CompanyFile
    template_name = 'tool/upload-company-file.html'
    form_class = CompanyFileForm
    success_url = reverse_lazy('tool:result')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['dict_files'] = self.request.session['dict_files']
        print(context['dict_files'])
        return context

    def form_valid(self, form):
        self.object = form.save()
        user = self.request.user
        self.object.user = user
        self.object.company = user.company
        self.object.name = self.object.file.name
        # self.request.session['report_id'] = self.object.pk
        # if not self.object.slug:
        #     self.object.slug = slugify(str(self.object.company) + "-" + get_random_string(length=32))
        self.request.session['company_file_pk'] = self.object.pk
        return super().form_valid(form)


'''
Webpage result:
'''


class ResultView(LoginRequiredMixin, TemplateView):
    """ View to access results from comparison """

    template_name = 'tool/result.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        #Preparing empty data
        transporters_profile_list = []
        transporters_list = []
        dict_errors = {}

        ''' TRANSPORTERS '''
        transporters_profile = Supplement.objects.filter(company=self.request.user.company).values_list(
            'transporter__name', flat=True)
        for profile in transporters_profile:
            transporters_profile_list.append(profile)



        ''' FILES '''
        # Company file
        context['company_file_pk'] = self.request.session['company_file_pk']
        company_file = get_object_or_404(CompanyFile, pk=context['company_file_pk'])
        company_file = company_file.file

        # File list
        dict_files = self.request.session['dict_files']

        for i in range(len(dict_files.get('pk'))):
            # Get variables and names
            pk = dict_files.get('pk')[i]

            #Handling transporters. If transporter is in list, then outputs result.
            transporter = dict_files.get('transporter')[i]
            transporters_list.append(transporter)
            transporter = Transporter.objects.get(name=transporter)

            #Managing header_row
            header_row = get_header_row(company=self.request.user.company, transporter=transporter)

            #Get actual transporter file
            transporter_file = TransporterFile.objects.get(pk=pk)
            transporter_file = transporter_file.file
            extension = os.path.splitext(transporter_file.name)[1]

            ''' Analysis '''
            'To make analysis, function analyze() needs to be called.' \
            'The function needs to be called with the company file, transporter file, the transporter and the company.'

            df = analyze(transporter_file=transporter_file,
                            company_file=company_file,
                            transporter=transporter,

src/tool/templates/tool/add-report.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="px-4 sm:px-6 lg:px-8 mt-11">
        <div class="sm:flex sm:items-center h-90">
            <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
                <div class="task-form-htmx">
                    <div class="sm:flex-auto">
                        <h1 class="text-xl font-semibold text-gray-900">Users</h1>
                        <p class="mt-2 text-sm text-gray-700">A list of all the users in your account including their
                            name, title, email and role.</p>

                    </div>
                    <div class="w-full max-w-7xl mx-auto px-4">
                        <form method="post" enctype="multipart/form-data" class="mt-5">
                            {% csrf_token %}
                            {{ form|crispy }}

                        <button type="submit" class="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">Submit</button>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

src/tool/templates/tool/download.html
{% extends 'base.html' %}

{% block content %}


{% endblock content %}

src/tool/templates/tool/home.html
{% extends 'base.html' %}



{% block content %}
        <div class="flex-1 flex items-stretch overflow-hidden">
        <main class="flex-1 overflow-y-auto">
        <!-- Primary column -->
        <section aria-labelledby="primary-heading" class="min-w-0 flex-1 h-full flex flex-col lg:order-last">
          <h1 id="primary-heading">Photos</h1>
          <!-- Your content -->
        </section>
      </main>
        </div>

{% endblock %}

src/tool/templates/tool/reports.html
{% extends 'base.html' %}

{% block content %}

<div class="px-4 sm:px-6 lg:px-8 mt-11">
  <div class="sm:flex sm:items-center h-90">
    <div class="sm:flex-auto">
      <h1 class="text-xl font-semibold text-gray-900">Users</h1>
      <p class="mt-2 text-sm text-gray-700">A list of all reports.</p>
    </div>
    <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
        <a href="{% url 'tool:add-report' %}" class="inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 sm:w-auto">Add report</a>
    </div>
  </div>
  <div class="-mx-4 mt-8 overflow-hidden shadow ring-1 ring-black ring-opacity-5 sm:-mx-6 md:mx-0 md:rounded-lg">
    <table class="min-w-full divide-y divide-gray-300">
      <thead class="bg-gray-50">
        <tr>
          <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Title</th>
          <th scope="col" class="hidden px-3 py-3.5 text-left text-sm font-semibold text-gray-900 sm:table-cell">Company</th>
          <th scope="col" class="hidden px-3 py-3.5 text-left text-sm font-semibold text-gray-900 lg:table-cell">Slug</th>
          <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Access URL</th>
          <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
            <span class="sr-only">Edit</span>
          </th>
        </tr>
      </thead>
      <tbody class="divide-y divide-gray-200 bg-white">
      {% for report in reports %}
        <tr>
          <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6">{{ report.title }}</td>
          <td class="hidden whitespace-nowrap px-3 py-4 text-sm text-gray-500 sm:table-cell">{{ report.company }}</td>
          <td class="hidden whitespace-nowrap px-3 py-4 text-sm text-gray-500 lg:table-cell">{{ report.slug }}</td>
          <td class="whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
            <a href="{% url 'tool:single-report' slug=report.slug %}" class="text-indigo-600 hover:text-indigo-900">Access</a>
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
</div>

    {% if reports_count == 0 %}
    <p>Il n'y a actuellement aucun rapport. Cliquez <a href="{% url 'tool:add-report' %}">ici</a> pour ajouter un rapport.</p>
    {% endif %}



{% endblock content %}

src/tool/templates/tool/result.html
{% extends 'base.html' %}

{% block content %}
    <p>Voici un exemple de réponse </p>
    <p>Vous trouverez le détail par transporteur ci-dessous. </p>
{#    <p>Sur un total de <b>{{ nb_rows }}</b> commandes, vous avez <b><u>{{ nb_errors }}</u></b> colis qui font l'objet d'une erreur.</p>#}
{#    <ul>#}
{#        <li>Pour cette commande, vous avez payé un total de <div style="font-size:18px;display:inline;color:darkred; font-weight: bold;">{{ total_amount }}€</div></li>#}
{#        <li>Le manque à gagner est de <div style="font-size:18px;display:inline;color:darkgreen; font-weight: bold;">{{ rows_errors_sum }}€</div></li>#}
{##}
{#    </ul>#}
{##}
{#    <p><a href="{% url 'tool:download' %}">Télécharger le rapport</a></p>#}

<ul>
    {% for key, value in dict_errors.items %}
        <li>{{ key }}</li>
            <ul>
                <li> Le montant de la commande totale est de <div style="font-size:18px;display:inline;color:darkred; font-weight: bold;">{{ value.total_amount }}€</div>.</li>
                <li> {{ value.nb_errors }} erreurs ont été relevées. </li>
                <li> Le manque à gagner est de <div style="font-size:18px;display:inline;color:darkgreen; font-weight: bold;">{{ value.rows_errors_sum }}€</div> pour cette commande.</li>
                <li><a href="{% url 'tool:download' slug=value.slug %}">Télécharger le rapport</a></li>

            </ul>
    {% endfor %}
</ul>


{% endblock content %}

src/tool/templates/tool/single-report.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block scripts %}

{% endblock scripts %}

{% block content %}
    <div class="px-4 sm:px-6 lg:px-8 mt-11">
        <div class="sm:flex sm:items-center h-90">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24"
                 stroke="#68ba9f" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round"
                      d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01"/>
            </svg>
            <div class="sm:flex-auto">

                <h1 class="text-xl font-semibold text-gray-900">Contrôle facturation <span
                        class="inline-flex items-center px-2.5 py-0.5 rounded-md text-sm font-medium bg-[#68ba9f] text-slate-100">{{ report_title }}</span></p>
            </div>
        </div>
        <br/>

        <!-- Card -->
        <div class="grid grid-cols-1">
            <div class="bg-white overflow-hidden shadow rounded-lg">
                <div class="p-5">
                    <div class="flex items-center">
                        <div class="flex-shrink-0">
                            <!-- Heroicon name: outline/scale -->
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24"
                                 stroke="#68ba9f" stroke-width="2">
                                <path stroke-linecap="round" stroke-linejoin="round"
                                      d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12"/>
                            </svg>
                        </div>
                        <div class="ml-5 w-0 flex-1">
                            <dl>
                                <dt class="text-sm font-medium text-gray-500 truncate">Importer le fichier des
                                    commandes
                                </dt>
                            </dl>
                        </div>
                    </div>
                </div>
                <div class="bg-gray-50 px-5 py-3">
                    <div class="text-sm">
                        <a href="#" class="font-medium text-cyan-700 hover:text-cyan-900"> Uploader le fichier </a>
                    </div>
                </div>
            </div>


        </div>
        <p>
            Liste des transporteurs pour cette société :
            {% for supplement in supplements %}
                <ul>
                    <li>{{ supplement.transporter }}</li>
                    <form enctype="multipart/form-data" method="post">
                        {% csrf_token %}
                        {{ transporter_form.file.as_widget }}
                    </form>
                </ul>
            {% endfor %}
        </p>
{% endblock content %}

src/tool/templates/tool/transporter-detail-edit.html
{% extends 'base.html' %}

{% block content %}
<p>Vous pouvez, si vous le souhaitez modifier les tarifs de ce transporteur :</p>

    <h1> Editer </h1>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
    <input type="submit" value="Editer">
    </form>

{% endblock content %}

src/tool/templates/tool/transporter-detail.html
{% extends 'base.html' %}

{% block content %}
<p>Veuillez choisir ci-dessous entre l'édition des tarifs transporteur ou l'upload d'un fichier transporteur :</p>

    <ul>
        <li><a href="{% url 'tool:edit-tarifs' slug=supplement.slug %}">Editer les tarifs</a></li>
    </ul>


{% endblock content %}

src/tool/templates/tool/transporters.html
{% extends 'base.html' %}

{% block content %}
<p>Veuillez choisir ci-dessous le transporteur concerné pour l'upload du fichier transporteur :</p>
{% for supplement in supplements %}
    <ul>
    {% if supplement.brand %}
        <li>{{ supplement.brand }} - {{ supplement.transporter }} </li>
    {% else %}
        <li><a href="{% url 'tool:tarifs' slug=supplement.slug %}">{{ supplement.transporter }}</a></li>
    {% endif %}
    </ul>
{% endfor %}
{% endblock content %}

src/tool/templates/tool/try.html
{% extends 'base.html' %}

{% block content %}
    <p>Test pour afficher les données : </p>


{% endblock content %}

src/tool/templates/tool/upload-company-file.html
{% extends 'base.html' %}


{% block content %}

    <form method="POST" enctype="multipart/form-data">

    <p>Veuillez uploader le fichier des commandes : </p>
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Submit</button>

{% endblock content %}

src/tool/templates/tool/upload-fichier-commandes.html
{% extends 'base.html' %}

{% block content %}
<form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Prochaine étape</button>
</form>
{% endblock content %}